name: uv_net
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - dgl-cuda11.0==0.6.1=py39_0
  - joblib==1.0.1=pyhd3eb1b0_0
  - matplotlib-base=3.4.2
  - matplotlib=3.4.2
  - occwl=1.0
  - python=3.9
  - pytorch-lightning=1.3
  - pytorch=1.8
  - scikit-learn
  - torchmetrics[version='0.3.*,0.3.2.*']
  - tqdm=4.59.0
  - trimesh=3.9.18
  - faiss-cpu
  - pandas
